### ISSUE TITLE
MONIT_API endpoint is requested like BMA !

### ISSUE THREAD

**Issue by librelois** [duniter/duniter4j#18]
@blavenie Ton nœud ES 88.189.14.141 requête constamment g1-monit.elois.org/node/summary sur 443, c'est à dire sur l'endpoint `MONIT_API` alors qu'il s'agit d'une url propre a `BASIC_MERKLED_API`...

Ça créer du trafic pour rien, mon module retournant une erreur 404 a chaque fois, je pense que tu a une erreur qui fait que l'endpoint MONIT_API est requêter alors qu'il ne devrait pas l'être, peut tu corriger ça ?

Ça me gène beaucoup car je viens d’implémenter un nouveau système d'alerte DDos sur mes serveur et je reçoit des warning à cause de ça donc je vais être obliger de bannir ton IP ou de diminuer le niveau de sensibilité...

Et c'est de plus encombrant dans les log : 
88.189.14.141 - - [06/Jul/2017:19:29:45 +0200] "GET /node/summary HTTP/1.1" 404 56 "-" "Apache-HttpClient/4.3.3 (java 1.5)"
88.189.14.141 - - [06/Jul/2017:19:32:39 +0200] "GET /node/summary HTTP/1.1" 404 56 "-" "Apache-HttpClient/4.3.3 (java 1.5)"
88.189.14.141 - - [06/Jul/2017:19:33:39 +0200] "GET /node/summary HTTP/1.1" 404 56 "-" "Apache-HttpClient/4.3.3 (java 1.5)"
88.189.14.141 - - [06/Jul/2017:19:34:21 +0200] "GET /node/summary HTTP/1.1" 404 56 "-" "Apache-HttpClient/4.3.3 (java 1.5)"
88.189.14.141 - - [06/Jul/2017:19:39:15 +0200] "GET /node/summary HTTP/1.1" 404 56 "-" "Apache-HttpClient/4.3.3 (java 1.5)"
88.189.14.141 - - [06/Jul/2017:19:42:19 +0200] "GET /node/summary HTTP/1.1" 404 56 "-" "Apache-HttpClient/4.3.3 (java 1.5)"
88.189.14.141 - - [06/Jul/2017:19:44:25 +0200] "GET /node/summary HTTP/1.1" 404 56 "-" "Apache-HttpClient/4.3.3 (java 1.5)"
88.189.14.141 - - [06/Jul/2017:19:48:52 +0200] "GET /node/summary HTTP/1.1" 404 56 "-" "Apache-HttpClient/4.3.3 (java 1.5)"
88.189.14.141 - - [06/Jul/2017:19:49:15 +0200] "GET /node/summary HTTP/1.1" 404 56 "-" "Apache-HttpClient/4.3.3 (java 1.5)"
88.189.14.141 - - [06/Jul/2017:19:51:13 +0200] "GET /node/summary HTTP/1.1" 404 56 "-" "Apache-HttpClient/4.3.3 (java 1.5)"

**Comment by blavenie** [comment]
ok je regardes ca ;)
