### ISSUE TITLE
Erreur d'extensions

### ISSUE THREAD

**Issue by mcl1234** [duniter/duniter4j#3]
Bonjour,

Je ne parviens pas à ajouter l'extension Duniter pour l'indexeur , car les versions de l'indexeur ne sont pas rétro-comptabiles pour ces extensions, et leur site ne présente pas de elasticSearch 2.3.3

ERROR: Plugin [duniter4j-elasticsearch] is incompatible with Elasticsearch [2.3.4]. Was designed for version [2.3.3]

**Comment by blavenie** [comment]
Bonjour à toi !
Oui, j'ai du aussi revenur en 2.3.3.

J'ai un gros travail pour mettre à jour la doc d'install.
Merci bcp de tester, cela m'aide à me motiver pour cela !
